### ISSUE TITLE
Team Change

### ISSUE THREAD

**Issue by VivianLi1** [RongYu98/Generic-Name#4]
(Copy pasting from my email) Right now, I have a super crude solution where basically every time the user clicks on the toggle button the team switches, but this does not account for the select function. So for example, when you have the toggle on blue and you select a red player, the next player that is added will still be red even if the toggle is blue. It's on line 989.

$("[name='change']").on('switchChange.bootstrapSwitch', function(event, state){
    changeColor();
});

I don't know which one of you did the team switching so I'm tagging both of you.

**Comment by igerstein** [comment]
Resolved.
