### ISSUE TITLE
Side Menu Partially Not Visible

### ISSUE THREAD

**Issue by RongYu98** [RongYu98/Generic-Name#6]
Whenever the window becomes smaller, the side menu with the choices is not resized. 
For example, when the window is resizes, the field resizes and becomes smaller, but the side menu thing doesn't move. When we scroll the page, it also doesn't scroll, preventing us from accessing the speed slider.
Solution: Scale/Resize the menu bar as well or allow it to be scrolled, with the first being preferable as it will match with the field.

**Comment by igerstein** [comment]
Resolved.
